# Generated by Django 4.2.4 on 2023-08-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_alter_fileupload_fileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='djangoapp/static')),
                ('video_name', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='djangoapp/static')),
                ('pdf_name', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
    ]
