# Generated by Django 4.2.4 on 2023-08-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka')], max_length=30)),
                ('english', models.BooleanField(default=False)),
                ('malayalam', models.BooleanField(default=False)),
                ('hindi', models.BooleanField(default=False)),
            ],
        ),
    ]
